version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: 'java-postgres'
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 20032612
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: 1ac90c348e3d
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db


volumes:
  db:
    driver: local